# Uncomment the next line to define a global platform for your project
platform :ios, '12.2'

target 'BMovies' do
  use_frameworks!

  pod 'Alamofire', '~> 4.8.2'
  pod 'Kingfisher'
  
  target 'BMoviesTests' do
      inherit! :search_paths
      
      pod 'Alamofire', '~> 4.8.2'
  end

end
